In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('logistics_shipments_dataset.csv')

In [5]:
df.head(50)

,Shipment_ID,Origin_Warehouse,Destination,Carrier,Shipment_Date,Delivery_Date,Weight_kg,Cost,Status,Distance_miles,Transit_Days
0,SH10000,Warehouse_MIA,San Francisco,UPS,2023-10-02,2023-10-04,25.7,67.46,Delivered,291,2
1,SH10001,Warehouse_MIA,Atlanta,DHL,2023-12-06,2023-12-09,38.9,268.85,Delivered,1225,3
2,SH10002,Warehouse_LA,Houston,DHL,2023-09-18,2023-09-20,37.2,74.35,Delivered,220,2
3,SH10003,Warehouse_BOS,Seattle,OnTrac,2023-01-26,2023-02-04,42.6,187.04,Delivered,1156,9
4,SH10004,Warehouse_SF,Dallas,OnTrac,2023-06-03,2023-06-06,7.9,120.01,Delivered,1017,3
5,SH10005,Warehouse_ATL,New York,FedEx,2023-09-13,2023-09-16,9.1,143.26,Delivered,898,3
6,SH10006,Warehouse_BOS,Houston,UPS,2023-10-19,2023-10-23,0.4,225.23,Delivered,1522,4
7,SH10007,Warehouse_CHI,Portland,Amazon Logistics,2023-02-27,2023-03-08,16.7,281.23,Delivered,2013,9
8,SH10008,Warehouse_HOU,Detroit,Amazon Logistics,2023-11-24,2023-12-01,15.1,341.93,Delivered,2072,7
9,SH10009,Warehouse_SF,Detroit,LaserShip,2023-01-19,2023-01-21,27.7,55.24,Delivered,214,2
10,SH10010,Warehouse_MIA,Chicago,FedEx,2023-02-02,2023-02-07,7.1,251.53,Delivered,1736,5
11,SH10011,Warehouse_ATL,Boston,Amazon Logistics,2023-05-28,2023-06-04,38.2,357.12,Delayed,2366,6
12,SH10012,Warehouse_SEA,New York,FedEx,2023-08-08,2023-08-13,34.4,121.14,Delivered,650,5
13,SH10013,Warehouse_NYC,Phoenix,UPS,2023-12-28,2024-01-03,20.7,272.48,Delivered,1574,6
14,SH10014,Warehouse_BOS,Miami,FedEx,2023-07-24,2023-07-30,12.5,266.08,Delivered,1849,6
15,SH10015,Warehouse_DEN,Minneapolis,OnTrac,2023-05-10,2023-05-16,28.6,221.21,Delivered,1489,6
16,SH10016,Warehouse_CHI,Detroit,USPS,2023-01-25,2023-01-26,24.1,60.27,Lost,283,1
17,SH10017,Warehouse_LA,San Francisco,OnTrac,2023-06-08,2023-06-11,43.2,80.60,In Transit,223,3
18,SH10018,Warehouse_ATL,Atlanta,OnTrac,2023-10-16,2023-10-25,6.3,124.52,Delivered,1055,9
19,SH10019,Warehouse_MIA,Portland,DHL,2023-01-16,2023-01-21,51.2,290.72,Delivered,1660,5
20,SH10020,Warehouse_MIA,Miami,FedEx,2023-08-10,2023-07-11,7.8,216.42,Delivered,1696,5
21,SH10021,Warehouse_SEA,Houston,LaserShip,2023-08-23,2023-08-27,29.6,216.63,Returned,1407,4
22,SH10022,Warehouse_CHI,San Francisco,USPS,2023-07-21,2023-07-23,15.2,67.11,Delivered,440,2
23,SH10023,Warehouse_SEA,Los Angeles,DHL,2023-10-26,2023-10-29,22.2,228.57,Delivered,1402,3
24,SH10024,Warehouse_DEN,Phoenix,USPS,2023-08-11,2023-08-15,5.3,37.32,Delivered,256,4
25,SH10025,Warehouse_NYC,Portland,UPS,2023-04-27,2023-04-29,40.0,124.29,Delivered,519,2
26,SH10026,Warehouse_DEN,Miami,UPS,2023-12-30,2024-01-01,8.7,73.52,Delivered,386,2
27,SH10027,Warehouse_DEN,Boston,USPS,2023-12-30,2024-01-05,10.1,309.59,Delayed,1986,5
28,SH10028,Warehouse_SF,Dallas,LaserShip,2023-12-15,2023-12-20,22.8,373.64,Delivered,2229,5
29,SH10029,Warehouse_SEA,Chicago,DHL,2023-06-27,2023-07-03,13.0,347.94,Delivered,2310,6
30,SH10030,Warehouse_SF,San Francisco,LaserShip,2023-11-04,NaN,28.5,109.33,Delivered,502,2
31,SH10031,Warehouse_BOS,Dallas,OnTrac,2023-07-04,2023-07-08,30.2,162.68,Delivered,1048,4
32,SH10032,Warehouse_CHI,New York,FedEx,2023-09-27,2023-10-01,11.3,206.19,Delivered,1551,4
33,SH10033,Warehouse_SF,Denver,USPS,2023-03-26,2023-04-02,15.8,66.35,Delayed,431,2
34,SH10034,Warehouse_SEA,Denver,OnTrac,2023-02-21,2023-02-23,10.7,76.52,Delivered,528,2
35,SH10035,Warehouse_BOS,Dallas,OnTrac,2023-07-16,2023-07-17,37.7,55.09,Lost,131,1
36,SH10036,Warehouse_ATL,Los Angeles,FedEx,2023-06-02,2023-06-18,27.9,123.81,Delayed,659,3
37,SH10037,Warehouse_SF,Dallas,Amazon Logistics,2023-11-06,2023-11-11,26.6,333.35,Delivered,2209,5
38,SH10038,Warehouse_SF,Detroit,LaserShip,2023-11-04,2023-11-10,30.7,282.71,Returned,1674,6
39,SH10039,Warehouse_MIA,New York,LaserShip,2023-12-08,NaN,65.2,284.81,Delivered,1204,3
40,SH10040,Warehouse_BOS,Denver,Amazon Logistics,2023-10-04,2023-10-10,13.4,209.01,Delivered,1550,6
41,SH10041,Warehouse_NYC,Los Angeles,UPS,2023-05-13,2023-05-17,31.9,263.06,Delivered,1696,4
42,SH10042,Warehouse_NYC,Los Angeles,USPS,2023-12-29,2024-01-01,37.8,129.73,Delivered,660,3
43,SH10043,Warehouse_SEA,New York,DHL,2023-03-09,2023-03-13,17.4,194.58,Delivered,1153,4
44,SH10044,Warehouse_CHI,San Francisco,OnTrac,2023-05-08,2023-05-11,4.7,49.68,Delivered,343,3
45,SH10045,Warehouse_NYC,Miami,LaserShip,2023-04-24,2023-04-29,29.7,245.98,Delivered,1973,5
46,SH10046,Warehouse_LA,Los Angeles,DHL,2023-09-05,2023-09-11,9.0,356.77,Delivered,2335,6
47,SH10047,Warehouse_SF,Dallas,USPS,2023-01-17,2023-01-20,25.4,127.22,Delivered,816,3
48,SH10048,Warehouse_SF,Phoenix,LaserShip,2023-04-23,2023-04-30,14.2,248.03,Delivered,1758,7
49,SH10049,Warehouse_MIA,Boston,UPS,2023-01-07,2023-01-11,84.1,251.24,Delivered,1010,4

In [6]:
df.describe()

         Weight_kg         Cost  Distance_miles  Transit_Days
count  2000.000000  1959.000000     2000.000000   2000.000000
mean     30.184800   205.161598     1275.868000      4.182500
std     124.967053   222.586082      691.382829      1.837902
min       0.000000    17.890000      101.000000      1.000000
25%      12.300000   117.710000      690.250000      3.000000
50%      20.700000   196.420000     1262.500000      4.000000
75%      33.925000   272.115000     1867.250000      5.000000
max    5404.200000  6562.210000     2499.000000     12.000000

In [9]:
df.isnull().value_counts()

Shipment_ID  Origin_Warehouse  Destination  Carrier  Shipment_Date  Delivery_Date  Weight_kg  Cost   Status  Distance_miles  Transit_Days
False        False             False        False    False          False          False      False  False   False           False           1928
                                                                                              True   False   False           False             40
                                                                    True           False      False  False   False           False             31
                                                                                              True   False   False           False              1
Name: count, dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Shipment_ID       2000 non-null   object
 1   Origin_Warehouse  2000 non-null   object
 2   Destination       2000 non-null   object
 3   Carrier           2000 non-null   object
 4   Shipment_Date     2000 non-null   object
 5   Delivery_Date     1968 non-null   object
 6   Weight_kg         2000 non-null   float64
 7   Cost              1959 non-null   float64
 8   Status            2000 non-null   object
 9   Distance_miles    2000 non-null   int64
 10  Transit_Days      2000 non-null   int64
dtypes: float64(2), int64(2), object(7)
memory usage: 172.0+ KB